# SCADA AI System - Production Configuration

system:
  name: "SCADA AI System"
  version: "2.0.0"
  environment: "production"
  log_level: "INFO"
  max_workers: 4
  timezone: "UTC"
  data_retention_days: 90

security:
  secret_key: "scada-ai-secret-key-change-in-production"
  encryption_enabled: true
  jwt_expiry_hours: 24
  max_login_attempts: 5
  session_timeout_minutes: 30
  ssl_enabled: false
  certificate_path: ""
  private_key_path: ""

protocols:
  modbus_tcp:
    enabled: true
    port: 502
    timeout: 10
  modbus_rtu:
    enabled: true
    baudrate: 9600
    timeout: 5
  dnp3:
    enabled: false
    port: 20000
  iec61850:
    enabled: false
    port: 102

monitoring:
  enabled: true
  websocket_port: 8001
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 85
    disk_usage: 90
    temperature: 70
  notification_channels:
    email: false
    sms: false
    webhook: true

analytics:
  enabled: true
  ml_models_enabled: true
  anomaly_detection: true
  predictive_maintenance: true
  model_update_interval_hours: 24
  training_data_days: 30

reporting:
  enabled: true
  formats: ["pdf", "excel", "html"]
  auto_generation: true
  schedule: "daily"
  output_directory: "reports"

compliance:
  audit_enabled: true
  standards: ["ISO27001", "IEC62443"]
  log_retention_days: 365
  integrity_checking: true

integration:
  erp_enabled: false
  mes_enabled: false
  cloud_enabled: false
  message_queue: "memory"

pipeline:
  queue_size: 1000
  batch_size: 100
  processing_threads: 2
  retry_attempts: 3
  timeout_seconds: 30

api:
  host: "0.0.0.0"
  port: 8081
  cors_enabled: true
  rate_limiting: true
  max_requests_per_minute: 100

database:
  type: "sqlite"
  name: "scada_ai.db"
  host: "localhost"
  port: 5432
  username: ""
  password: ""
  pool_size: 10
